# Model Config
model_name: "split_lr_narrowpredictor_gradientmonitor_v7_check2"
use_cls_token: False
use_contrastive_loss: False
constrastive_loss_weight: 1.0

# Training Configs
batch_size: 4
num_workers: 1
num_epochs: 300
seed: 42
warmup: 40
start_lr: 0.0002
lr: 0.000625
final_lr: 1.0e-6
num_samples_per_epoch: 1024
ema:
  - 0.998
  - 1.0
ipe_scale: 1.25
reg_coeff: 0

# Saving progress
ckpt_saving: True
ckpt_interval: 5
resume_from_ckpt: False
wandb_log: True

# MAE Config
x_encoder_start_masking_ratio: 0.85
x_encoder_end_masking_ratio: 0.85
y_encoder_mask_ratio: 0.85
use_rope_emb: False
masking_strategy: "MNI"

# Model Config
depth: 12
dim: 512
patch_size: 8
frame_patch_size: 4
use_rope_emb: False
embed_dim: 384
mlp_dim: 1536
num_heads: 12
# dim_head = embed_dim / num_heads
dim_head: 32


# Data Config
image_size: [88, 104, 72] # Image Size
num_frames: 4
train_urls: ["/scratch/gpfs/ks9249/nsdfoundation/wds/{000005..000099}.tar"]
test_urls: "/scratch/gpfs/ks9249/nsdfoundation/wds/{000000..000004}.tar"
is_s3: False
