# Model Config
model_name: "test_3" #"patch8_ViTS_1gpu_8gbs_50epoch"
use_cls_token: False
use_contrastive_loss: False
constrastive_loss_weight: 1.0

# Training Configs
global_batch_size: 4
num_workers: 16
max_steps: 1000
eval_per_n_steps: 200
limit_val_batches: 80
seed: 42
max_lr: 3.0e-3 # Keep the x.0 else will be converted to string

# Saving progress
ckpt_saving: True
ckpt_interval: 50
resume_from_ckpt: False
wandb_log: True

# MAE Config
tube_start_masking_ratio: 0.95
tube_end_masking_ratio: 0.95
decoder_mask_ratio: 0.95

# Model Config
encoder_model: "vit_base"
decoder_model: "vit_small"
patch_size: 8
frame_patch_size: 1
use_rope_emb: False
masking_strategy: "MNI"

# Data Config
img_size: [88, 104, 72] # Image Size
num_frames: 4
is_s3: False
test_urls: s3://proj-fmri/fmri_foundation_datasets/NSD_MNI_wds/{000000..000494}.tar
train_urls: s3://proj-fmri/fmri_foundation_datasets/NSD_MNI_wds/000496.tar
