# Model Config
model_name: "patch8_100eps_4gpu_accelerate_b"
use_cls_token: False
use_contrastive_loss: False
constrastive_loss_weight: 1.0

# Training Configs
global_batch_size: 8
num_workers: 4
num_epochs: 100
seed: 42
max_lr: 3.0e-5 # Keep the x.0 else will be converted to string
num_samples_per_epoch: 1024
cache_dir: "cache/"

# Saving progress
ckpt_saving: True
ckpt_interval: 50
resume_from_ckpt: False
wandb_log: True

# MAE Config
tube_start_masking_ratio: 0.75
tube_end_masking_ratio: 0.75
decoder_mask_ratio: 0.75

# Model Config
encoder_model: "vit_base"
decoder_model: "vit_small"
patch_size: 8
frame_patch_size: 1
use_rope_emb: False
use_4d_conv: False

# Data Config
img_size: [64, 64, 48] # Image Size
num_frames: 4
train_urls: "s3://proj-fmri/fmri_foundation_datasets/openneuro/{000005..000664}.tar"
test_urls: "s3://proj-fmri/fmri_foundation_datasets/openneuro/{000000..000004}.tar"