# Model Config
model_name: "downstream_framepatchsize4_bs8_300ep_contr_nolinear"
mae_model_name: "framepatchsize1_4gpu_bs8_300ep_NEWcont_3e8_norm_rope_LONG"

# Training Configs
global_batch_size: 32
mixed_precision: "fp16"
num_epochs: 12
seed: 42
max_lr: 3.0e-4 # Keep the x.0 else will be converted to string
multi_subject: False
multisubject_ckpt: None

# Saving progress
ckpt_saving: False
ckpt_interval: 99
resume_from_ckpt: False
wandb_log: False

# Model Config
in_dim: 393216
hidden_dim: 2056
drop: .15
mixup_pct: 0.00

# Data Config
nsd_wds_path: "/weka/proj-fmri/shared/mindeyev2_dataset/wds"
nsd_raw_path: "/weka/proj-fmri/shared/mindeyev2_dataset"
nsd_image_path: "/weka/proj-fmri/shared/mindeyev2_dataset"
num_sessions: 40