# Model Config
model_name: "pretrain_framepatchsize4"
mae_model_name: "framepatchsize4_bs8_300ep"

# Training Configs
global_batch_size: 32
mixed_precision: "fp16"
num_epochs: 12
seed: 42
max_lr: 3.0e-4 # Keep the x.0 else will be converted to string
multi_subject: False
multisubject_ckpt: None

# Saving progress
ckpt_saving: False
ckpt_interval: 99
resume_from_ckpt: False
wandb_log: True

# Model Config
in_dim: 370176
hidden_dim: 512
drop: .15
mixup_pct: 0.33

# Data Config
nsd_wds_path: "/weka/proj-fmri/shared/mindeyev2_dataset/wds"
nsd_raw_path: "/weka/proj-fmri/shared/mindeyev2_dataset"
nsd_image_path: "/weka/proj-fmri/shared/mindeyev2_dataset"
num_sessions: 40