model_name: "flat_probe_Linear_normed"
hcp_flat_path: "/weka/proj-fmri/shared/hcp_flat"

decoder_embed_dim: 512
num_frames: 16
mask_ratio: .75
pred_t_dim: 8
t_patch_size: 2
cls_embed: True
no_qkv_bias: False
sep_pos_embed: True
trunc_init: False
norm_pix_loss: False

# Training Configs
batch_size: 32
num_workers: 10
num_epochs: 100
seed: 42
base_lr: 1.0e-3 # Keep the x.0 else will be converted to string
num_samples_per_epoch: 200000
probe_num_samples_per_epoch: 50000
test_num_samples_per_epoch: 50000
grad_clip: 1.0

# Saving progress
ckpt_saving: False
ckpt_interval: 20 # in epochs
print_interval: 20 # in steps
resume_from_ckpt: True
wandb_log: True